name: Deploy to prod

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: amazing-app
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.push-image.outputs.imageid }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node
        uses: actions/setup-node@v5
      - name: Test build
        run: |
          npm install
          echo "ACCESS_TOKEN=${{ secrets.DEPLOY_TOKEN }}" > .env
          npm run build

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push-image
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        run: echo "Deploying image ${{ needs.build.outputs.image_tag }} to production"
      - name: Deploy to prod
        uses: CND-Bergen/cnd-deploy-action@main
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          image: ${{ needs.build.outputs.image }}
