name: Handle Pull Requests

on:
  pull_request:

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'
          token: ${{ secrets.NPMJS_TOKEN }}
      - name: Running tests in PR
        run: npm run build && npm run test
      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .
          retention-days: 2